// <auto-generated />
namespace PTPMQLbtl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Creat_Table_Hoadon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creat_Table_Hoadon));
        
        string IMigrationMetadata.Id
        {
            get { return "202104220342269_Creat_Table_Hoadon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
