// <auto-generated />
namespace PTPMQLbtl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Creat_Table_Donhang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creat_Table_Donhang));
        
        string IMigrationMetadata.Id
        {
            get { return "202104200403419_Creat_Table_Donhang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
