// <auto-generated />
namespace PTPMQLbtl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Creat_Table_Khachhang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creat_Table_Khachhang));
        
        string IMigrationMetadata.Id
        {
            get { return "202104200414257_Creat_Table_Khachhang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
